name: no problem
on: issue_comment

jobs:
  echo-body:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Print
        run: |
          echo "$BODY"
        env:
          BODY: ${{ github.event.issue.body }}
