name: problem
on: issue_comment

jobs:
  echo-body:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Print
        run: |
          echo '${{ github.event.issue.body }}'
